" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
" source $VIMRUNTIME/defaults.vim

if &compatible
    set nocompatible
endif
set encoding=utf-8
set ttyfast
set lazyredraw
syntax on
filetype plugin indent on
set clipboard=unnamedplus
set ruler
set number
" set relativenumber
" augroup numbertoggle
"    autocmd!
"    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
"    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
" augroup END
set showmode
set laststatus=2
set modelines=0
set showcmd
set wildmenu

set backspace=indent,eol,start
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch

set backupdir=/tmp//
set undodir=/tmp//
set directory=/tmp//

if has('termguicolors')
    set termguicolors
endif
set background=dark
let g:gruvbox_material_background='medium'
" let g:gruvbox_material_enable_italic=0
" let g:gruvbox_material_disable_italic_comment=1
" let g:gruvbox_material_transparent_background=1
colorscheme gruvbox-material
